services:
    dummy_source:
        image: dummy_source:latest
        container_name: dummy_source
        build:
            context: .
        restart: unless-stopped
        privileged: true
        tty: true
        stdin_open: true
        network_mode: bridge
        ipc: host
        pid: host
        environment:
            - "PUBLISH_IP=multitrack_core"
            - "PUBLISH_PORT=8081"
            - "LISTEN_PORT=8500"
        ports:
            - "8500:8500"
