services:
    dummy_source:
        image: dummy_source:latest
        container_name: dummy_source
        build:
            context: .
        restart: unless-stopped
        privileged: true
        tty: true
        stdin_open: true
        network_mode: host
        ipc: host
        pid: host
        environment:
            - "PUBLISH_IP=127.0.0.1"
            - "PUBLISH_PORT=8000"
            - "LISTEN_PORT=8500"
