services:
  maptiles_server:
    image: maptiles_server:latest
    container_name: maptiles_server
    build:
      context: .
    restart: unless-stopped
    tty: true
    stdin_open: true
    environment:
      - "PORT=3000"
    ports:
      - "3000:3000"