services:
  multitrack_core:
    image: multitrack_core:latest
    container_name: multitrack_core
    build:
      context: .
    restart: unless-stopped
    tty: true
    stdin_open: true
    network_mode: bridge
    privileged: true
    ipc: host
    pid: host
    environment:
      - "GUI_PORT=8000"
      - "GUI_WSS_PORT=8001"
      - "PLUGIN_PORT=8081"
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8081:8081"