services:
    dummy_source:
        image: nxdn_source:latest
        container_name: nxdn_source
        build:
            context: .
        restart: unless-stopped
        privileged: true
        tty: true
        stdin_open: true
        network_mode: bridge
        ipc: host
        pid: host
        environment:
            - "PUBLISH_IP=multitrack_core"
            - "PUBLISH_PORT=8081"
            - "LISTEN_PORT=8600"
        ports:
            - "8600:8600"
        volumes:
            - /dev/:/dev/
