services:
  dummy_sink:
    image: dummy_sink:latest
    container_name: dummy_sink
    build:
      context: .
    restart: unless-stopped
    tty: true
    stdin_open: true
    environment:
      - "LISTEN_PORT=8000"
    ports:
      - "8000:8000"
