services:
  multitrack_core:
    image: multitrack_core:latest
    container_name: multitrack_core
    build:
      context: ./multitrack_core
    restart: unless-stopped
    tty: true
    stdin_open: true
    privileged: true
    networks:
      - multitrack_network
    ipc: host
    pid: host
    environment:
      - "GUI_PORT=8000"
      - "GUI_WSS_PORT=8001"
      - "PLUGIN_PORT=8081"
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8081:8081"
  dummy_source:
    image: dummy_source:latest
    container_name: dummy_source
    build:
        context: ./dummy_source
    restart: unless-stopped
    privileged: true
    tty: true
    stdin_open: true
    networks:
      - multitrack_network
    ipc: host
    pid: host
    environment:
        - "PUBLISH_IP=multitrack_core"
        - "PUBLISH_PORT=8081"
        - "LISTEN_PORT=8500"
    ports:
        - "8500:8500"

networks:
  multitrack_network:
    driver: bridge